#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/swift-rustup-toolchain.sh"
career_swift_select_rustup_toolchain

PACKAGE_DIR="$ROOT_DIR/swift/CareerCoreSwift"
ARTIFACTS_DIR="$PACKAGE_DIR/Artifacts"
XCFRAMEWORK_PATH="$ARTIFACTS_DIR/CareerCoreFFI.xcframework"
BUILD_DIR="${CARGO_TARGET_DIR:-$ROOT_DIR/target}/career-swift"
GENERATED_DIR="$BUILD_DIR/generated"
HEADERS_DIR="$BUILD_DIR/headers"
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$ROOT_DIR/target}"

readonly MACOS_TARGET="aarch64-apple-darwin"
readonly IOS_TARGET="aarch64-apple-ios"
readonly IOS_SIMULATOR_TARGET="aarch64-apple-ios-sim"
readonly LIBRARY_NAME="libcareer_swift.a"

export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-13.0}"
export IPHONEOS_DEPLOYMENT_TARGET="${IPHONEOS_DEPLOYMENT_TARGET:-16.0}"

for command in grep python3 sed shasum xcodebuild; do
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "error: required command is unavailable: $command" >&2
    exit 2
  fi
done

for target in "$MACOS_TARGET" "$IOS_TARGET" "$IOS_SIMULATOR_TARGET"; do
  career_swift_require_rust_target "$target"
done

rm -rf "$BUILD_DIR" "$XCFRAMEWORK_PATH"
mkdir -p "$GENERATED_DIR" "$HEADERS_DIR" "$ARTIFACTS_DIR" "$PACKAGE_DIR/Sources/CareerCore"

for target in "$MACOS_TARGET" "$IOS_TARGET" "$IOS_SIMULATOR_TARGET"; do
  "$CAREER_SWIFT_CARGO" build \
    --locked \
    --release \
    --package career-swift \
    --lib \
    --target "$target" \
    --target-dir "$CARGO_TARGET_DIR"
done

MACOS_LIBRARY="$CARGO_TARGET_DIR/$MACOS_TARGET/release/$LIBRARY_NAME"
IOS_LIBRARY="$CARGO_TARGET_DIR/$IOS_TARGET/release/$LIBRARY_NAME"
IOS_SIMULATOR_LIBRARY="$CARGO_TARGET_DIR/$IOS_SIMULATOR_TARGET/release/$LIBRARY_NAME"

"$CAREER_SWIFT_CARGO" run \
  --quiet \
  --locked \
  --package career-swift \
  --features bindgen \
  --bin career-swift-bindgen \
  -- \
  "$MACOS_LIBRARY" \
  "$GENERATED_DIR" \
  --swift-sources \
  --headers \
  --modulemap \
  --module-name CareerCoreFFI \
  --modulemap-filename module.modulemap \
  --metadata-no-deps

normalize_generated_header() {
  local source_path="$1"
  local output_path="$2"
  {
    echo "// Generated by pinned UniFFI 0.30.0 for career-swift. Do not edit."
    echo
    tail -n +4 "$source_path" | sed 's/[[:space:]]*$//'
  } > "$output_path"
}

grep -q '^module CareerCoreFFI {' "$GENERATED_DIR/module.modulemap"
grep -q '^#if canImport(CareerCoreFFI)$' "$GENERATED_DIR/CareerCore.swift"

normalize_generated_header \
  "$GENERATED_DIR/CareerCore.swift" \
  "$PACKAGE_DIR/Sources/CareerCore/CareerCore.swift"
normalize_generated_header \
  "$GENERATED_DIR/CareerCoreFFI.h" \
  "$HEADERS_DIR/CareerCoreFFI.h"
cp "$GENERATED_DIR/module.modulemap" "$HEADERS_DIR/module.modulemap"

xcodebuild -create-xcframework \
  -library "$MACOS_LIBRARY" -headers "$HEADERS_DIR" \
  -library "$IOS_LIBRARY" -headers "$HEADERS_DIR" \
  -library "$IOS_SIMULATOR_LIBRARY" -headers "$HEADERS_DIR" \
  -output "$XCFRAMEWORK_PATH"
python3 - "$XCFRAMEWORK_PATH/Info.plist" <<'PY'
from pathlib import Path
import plistlib
import sys

path = Path(sys.argv[1])
with path.open("rb") as file:
    document = plistlib.load(file)
document["AvailableLibraries"].sort(key=lambda item: item["LibraryIdentifier"])
with path.open("wb") as file:
    plistlib.dump(document, file, fmt=plistlib.FMT_XML, sort_keys=True)
PY

WORKSPACE_METADATA_PATH="$BUILD_DIR/cargo-metadata.json"
ARTIFACT_METADATA_PATH="$ARTIFACTS_DIR/CareerCoreFFI.metadata.json"
"$CAREER_SWIFT_CARGO" metadata \
  --locked \
  --format-version 1 \
  --no-deps \
  --manifest-path "$ROOT_DIR/Cargo.toml" \
  > "$WORKSPACE_METADATA_PATH"
python3 - \
  "$WORKSPACE_METADATA_PATH" \
  "$ARTIFACT_METADATA_PATH" \
  "$MACOSX_DEPLOYMENT_TARGET" \
  "$IPHONEOS_DEPLOYMENT_TARGET" <<'PY'
from pathlib import Path
import json
import sys

workspace_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
workspace = json.loads(workspace_path.read_text())
package = next(item for item in workspace["packages"] if item["name"] == "career-swift")
document = {
    "schema_version": "career.swift_artifact_metadata.v1",
    "package_version": package["version"],
    "uniffi_version": "0.30.0",
    "deployment_targets": {
        "macos": sys.argv[3],
        "ios": sys.argv[4],
    },
    "rust_targets": [
        "aarch64-apple-darwin",
        "aarch64-apple-ios",
        "aarch64-apple-ios-sim",
    ],
}
output_path.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n")
PY

CHECKSUM_PATH="$ARTIFACTS_DIR/CareerCoreFFI.sha256"
(
  cd "$ARTIFACTS_DIR"
  : > "$(basename "$CHECKSUM_PATH")"
  shasum -a 256 "$(basename "$ARTIFACT_METADATA_PATH")" \
    >> "$(basename "$CHECKSUM_PATH")"
  while IFS= read -r file; do
    shasum -a 256 "$file" >> "$(basename "$CHECKSUM_PATH")"
  done < <(find "$(basename "$XCFRAMEWORK_PATH")" -type f | LC_ALL=C sort)
  test -s "$(basename "$CHECKSUM_PATH")"
  shasum -a 256 -c "$(basename "$CHECKSUM_PATH")"
)

printf 'Built %s\n' "$XCFRAMEWORK_PATH"
printf 'Checksums: %s\n' "$CHECKSUM_PATH"
